find_path(GLEW_INCLUDE_DIR NAMES GL PATHS include)
find_library(GLEW_LIBRARY NAMES GLEW libGLEW glew32 PATHS lib )

MESSAGE("** GLEW FOUND BY CONAN")
SET(GLEW_FOUND TRUE)
MESSAGE("** FOUND GLEW:  ${GLEW_LIBRARY}")
MESSAGE("** FOUND GLEW INCLUDE:  ${GLEW_INCLUDE_DIR}")

set(GLEW_INCLUDE_DIRS ${GLEW_INCLUDE_DIR})
set(GLEW_LIBRARIES ${GLEW_LIBRARY})

mark_as_advanced(GLEW_LIBRARY GLEW_INCLUDE_DIR)

set(GLEW_MAJOR_VERSION "1")
set(GLEW_MINOR_VERSION "13")
set(GLEW_PATCH_VERSION "0")
