find_path(OGG_INCLUDE_DIR NAMES ogg PATHS include)
find_library(OGG_LIBRARY NAMES ogg libogg_static PATHS lib )

MESSAGE("** OGG FOUND BY CONAN")
SET(OGG_FOUND TRUE)
MESSAGE("** FOUND OGG:  ${OGG_LIBRARY}")
MESSAGE("** FOUND OGG INCLUDE:  ${OGG_INCLUDE_DIR}")

set(OGG_INCLUDE_DIRS ${OGG_INCLUDE_DIR})
set(OGG_LIBRARIES ${OGG_LIBRARY})

mark_as_advanced(OGG_LIBRARY OGG_INCLUDE_DIR)

set(OGG_MAJOR_VERSION "1")
set(OGG_MINOR_VERSION "3")
set(OGG_PATCH_VERSION "2")
