find_path(GLM_INCLUDE_DIR NAMES glm PATHS include)

MESSAGE("** GLM FOUND BY CONAN")
SET(GLM_FOUND TRUE)
MESSAGE("** SETTING GLM INCLUDE:  ${GLM_INCLUDE_DIR}")

set(GLM_INCLUDE_DIRS ${GLM_INCLUDE_DIR})

mark_as_advanced(GLM_INCLUDE_DIR)

set(GLM_MAJOR_VERSION "0")
set(GLM_MINOR_VERSION "9")
set(GLM_PATCH_VERSION "8")

